# Generated by Django 5.2.1 on 2025-05-18 12:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emotions',
            field=models.JSONField(blank=True, default=list, validators=[api.models.validate_emotions]),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.JSONField(blank=True, default=list, validators=[api.models.validate_tags]),
        ),
    ]
